services:
  db:
    image: mysql:8
    container_name: sso-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: sso-flask
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: sso-react
    ports:
      - "3000:80"
    # REMOVEMOS A VARIÁVEL DE AMBIENTE DAQUI
    depends_on:
      - backend

volumes:
  db_data: