services:
  db:
    # --- LINHA ALTERADA ---
    # Fixamos a versão para 8.0, que é 100% compatível
    image: mysql:8.0
    container_name: sso-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      # MYSQL_USER: ${DB_USER}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sso_network

  backend:
    build:
      context: ./backend
    container_name: sso-flask
    ports:
      - "5000:5000"
    env_file:
      - .env
    command: ["/app/wait-for-db.sh", "flask", "run", "--host=0.0.0.0"]
    depends_on:
      - db
    networks:
      - sso_network

  frontend:
    build:
      context: ./frontend
    container_name: sso-react
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - sso_network

volumes:
  db_data:

networks:
  sso_network:
    driver: bridge