"""Adiciona cargo_id a usuarios

Revision ID: 72bd2413fc0f
Revises: 
Create Date: 2025-10-01 18:30:49.350273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72bd2413fc0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exames', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('exames_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('observacoes')
        batch_op.drop_column('colaborador_id')
        batch_op.drop_column('tipo_exame')
        batch_op.drop_column('data_agendamento')
        batch_op.drop_column('data_realizacao')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cargo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cargos', ['cargo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cargo_id')

    with op.batch_alter_table('exames', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_realizacao', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('data_agendamento', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('tipo_exame', mysql.ENUM('ADMISSIONAL', 'PERIODICO', 'RETORNO', 'DEMISSIONAL'), nullable=False))
        batch_op.add_column(sa.Column('colaborador_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('observacoes', mysql.TEXT(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('exames_ibfk_1'), 'usuarios', ['colaborador_id'], ['id'])

    # ### end Alembic commands ###
